var GAME_LEVELS = [
  ["   x                                                                     x      ",
   "   x                                                                     x      ",
   "   xxxx                                                                  x      ",
   "   x                                                                     x      ",
   "   x a         o o                                                       x      ",
   "   xxxx                                                                  x      ",
   "   x       xx!!!x!!!xx        o    o                                     x      ",
   "   x        xxxxxxxxx        xxxxxxxxxxx                                 x      ",
   "   x                                          xx   oo                    x      ",
   "   x                                               xx                    x      ",
   "   x                                                                     x      ",
   "   x                                                                     x      ",
   "   x                                                                     x      ",
   "   x        xx                               xx                          x      ",
   "   x oo          x     oo                                                x      ",
   "   xxxx                xx                                                x      ",
   "   x                                              xx                     x      ",
   "   x                                                                     x      ",
   "   x                                                                     x      ",
   "   x                              o   o                                  x      ",
   "   x@               a             xxxxxxxxx!!!!xxxxxxxxx!!!!xxxxxxxxxx   x      ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      ",
   "                                                                                "],

  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                         !                                      ",
   "                                         !                                      ",
   "              oo                         !                          x           ",
   "            sssss                        !                         ax           ",
   "                             !    oo              oo         xxxs sxx           ",
   "                     o       !                    sss  !!!ss                    ",
   "       xx            s     ss!ss            xxx                                 ",
   "  @                          !                                                  ",
   "sssss                        !o    ssssss!                        ooo           ",
   "ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
   "                                                                                ",],

   ["                    !                         ",
    "                    !                         ",
    "                    !                         ",
    "                    x            a            ",
    "                    x    o      xxx      o    ",
    "               xxxx !   sss             sss   ",
    "   o        o     x !                         ",
    "  sss      sss    x !          ssoss          ",
    "                  x !!!!!!!!!!!!!o!!!!!!!!!!!!",
    "                  x !            o            ",
    "        @         x !!!                       ",
    "       xxx        x             xxx           ",
    "                  x                           ",
    "!!!!!!sssss!!!!!!!xxxxxxxxxxsssssssssssxxxxxxx"],

   ["                                                                                ",
    "                                                                                ",
    "                    xxx       x        x     x    xxxx                          ",
    "                  xx         x x      x x   x x   x                             ",
    "                 x           x x      x x   x x   x                             ",
    "                 x     xxx  x   x    x   x x   x  xxxx                          ",
    "                 x       x  xxxxx    x   x x   x  x                             ",
    "                  x    xx  x     x  x     x     x x                             ",
    "                   xxxx    x     x  x     x     x xxxx                          ",
    "                                                                                ",
    "                                                                                ",
    "                              xxx       x       x   xxxxxxxx  xxxxxxx           ",
    "                            xx   xx     x       x   x         x      xx         ",
    "                           x       x    x       x   x         x        x        ",
    "                          x         x    x     x    x         x        x        ",
    "                          x         x    x     x    x         x      xx         ",
    "                         x           x   x     x    x         xxxxxxxx          ",
    "                         x           x    x   x     xxxxxxxx  x    x            ",
    "                         x           x    x   x     x         x     x           ",
    "                          x         x     x   x     x         x      x          ",
    "                          x         x      x x      x         x       x         ",
    "                           x       x       x x      x         x        x        ",
    "                            xx   xx        x x      x         x         x       ",
    "                              xxx           x       xxxxxxxx  x          x      ",
    "     @                                                                          ",
    "                                                                                ",
    " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
